swagger: "2.0"
info:
  title: "Inventory Microservice"
  description: "API for user accounts."
  version: "1.1.0"
  contact:
    email: "aditya.7sinha@gmail.com"
host: "localhost"
basePath: "/inventory-service/v1"
schemes:
  - http
consumes:
  - application/json;charset=utf-8
produces:
  - application/json;charset=utf-8
tags:
  - name: event
    description: "Everything about an event"
  - name: events
    description: "Everything about list of events"
  - name: issue
    description: "Everything about an issue"
  - name: issues
    description: "Everything about list of issues"
paths:
  /event:
    post:
      tags:
        - event
      summary: "This operation is to create event"
      parameters:
        - in: "body"
          name: "body"
          description: "Event object that needs to be added to the events"
          required: true
          schema:
            $ref: "#/definitions/Event_Create"
      responses:
        "201":
          description: "Event Created"
          schema:
            $ref: "#/definitions/Event"
        "401":
          description: "Invalid"
          schema:
            $ref: "#/definitions/Error"
    patch:
      tags:
        - event
      summary: "This operation is to patch event"
      parameters:
        - in: "body"
          name: "body"
          description: "Event object that needs to be added to the events"
          required: true
          schema:
            $ref: "#/definitions/Event_Create"
      responses:
        "201":
          description: "Event Updated"
          schema:
            $ref: "#/definitions/Event"
        "401":
          description: "Invalid"
          schema:
            $ref: "#/definitions/Error"
    put:
      tags:
        - event
      summary: "This operation is to put event"
      parameters:
        - in: "body"
          name: "body"
          description: "Event object that needs to be added to the events"
          required: true
          schema:
            $ref: "#/definitions/Event_Create"
      responses:
        "201":
          description: "Event Put"
          schema:
            $ref: "#/definitions/Event"
        "401":
          description: "Invalid"
          schema:
            $ref: "#/definitions/Error"
  /event/{eventid}:
    get:
      summary: "retrieving Event by Id"
      description: "This operation retrieves a Event entity."
      tags:
        - "event"
      parameters:
        - name: "eventid"
          description: "identification of the user who creates entity"
          required: true
          type: string
          in: path
      responses:
        "201":
          description: "Success"
          schema:
            $ref: "#/definitions/Event"
        "401":
          description: "Not Found"
          schema:
            $ref: "#/definitions/Error"
definitions:
  Event_Create:
    type: "object"
    description: "Event is the created"
    required:
      - userId
    properties:
      user_id:
        type: "string"
        description: "user id with which creates the event"
      name:
        type: "string"
        description: "name of the event"
      time_of_event:
        type: "string"
        description: "time of event"
      short_description:
        type: "string"
        description: "short description of event"
      summary:
        type: "string"
        description: "long summary of the event"
      event_location:
        $ref: "#/definitions/Event_Location"
      country:
        type: "string"
        description: "country of the event"
  Event_Location:
    type: "object"
    description: "location of the event's place or origin"
    properties:
      latitude:
        type: "string"
        description: "latitude of home_location"
      longitude:
        type: "string"
        description: "longitude of home_location"
      address:
        type: "string"
        description: "location of user entered by user manually"
  Event:
    type: "object"
    description: "returned event details"
    properties:
      user_id:
        type: "string"
        description: "user id with which created the event"
      event_id:
        type: "string"
        description: "event id of created event"
      name:
        type: "string"
        description: "name of the event"
      time_of_event:
        type: "string"
        description: "time of event"
      short_description:
        type: "string"
        description: "short description of event"
      summary:
        type: "string"
        description: "long summary of the event"
      event_location:
        $ref: "#/definitions/Event_Location"
      country:
        type: "string"
        description: "country of the event"
  Error:
    type: "object"
    description: "error codes"
    properties:
      code:
        type: "string"
        description: "returned code"
      message:
        type: "string"
        description: "returned message by the user"